# Pre-commit Configuration - Prevent Credential Commits
# Run: pip install pre-commit && pre-commit install

repos:
  # GitLeaks - Secret Detection
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks

  # detect-secrets - Additional Secret Detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

  # General Python/Code Quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  # Custom credential checker
  - repo: local
    hooks:
      - id: credential-checker
        name: Credential Checker
        entry: scripts/check-credentials.sh
        language: script
        files: \.(py|sql|md|json|yaml|yml|toml|env)$
        pass_filenames: true