# dbt project configuration for order tracking sync
name: 'order_tracking'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'order_tracking'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  order_tracking:
    staging:
      +materialized: incremental
    intermediate:
      +materialized: table
    mart:
      +materialized: incremental

tests:
  +store_failures: true
  +schema: settlement_dws

vars:
  # Schema configuration
  raw_schema: 'settlement_public'
  staging_schema: 'settlement_ods'
  mart_schema: 'settlement_ods'       # schema for mart tables and hist tables

  # 6-month hist periods — ADD one entry here every 1 Jan and 1 Jul.
  # Also: create the new hist tables in Redshift (DDL in order_tracking_final_design.md §15)
  #        update mart_uti step 1 table name (latest hist_uti for reactivation cleanup)
  #        add step 2 INSERT blocks to mart_uni_tracking_info and mart_uni_tracking_spath
  hist_periods:
    - name: '2025_h2'
      start: '2025-07-01'
      end:   '2026-01-01'
    # - name: '2026_h1'        # add this on 1 Jan 2026 (when first data ages into this window)
    #   start: '2026-01-01'
    #   end:   '2026-07-01'
    # - name: '2026_h2'        # add this on 1 Jul 2026
    #   start: '2026-07-01'
    #   end:   '2027-01-01'
