# dbt project configuration for order tracking sync
name: 'order_tracking'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'order_tracking'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  order_tracking:
    staging:
      +materialized: incremental
    intermediate:
      +materialized: table

tests:
  +store_failures: true
  +schema: settlement_dws

vars:
  # Configuration variables
  raw_schema: 'settlment_public'
  staging_schema: 'settlement_ods'
