# US Data Warehouse Settlement to Redshift Public Pipeline
# Clear naming: us_dw_settlement_2_public_pipeline

pipeline:
  name: "us_dw_settlement_2_public"
  description: "US Data Warehouse Settlement DB → Redshift Public Schema"
  source: "US_DW_RO_SSH"           # settlement database
  target: "redshift_default"       # public schema
  version: "1.2.0"
  
  processing:
    strategy: "sequential"
    batch_size: 50000
    timeout_minutes: 300
    max_parallel_tables: 4
  
  s3:
    isolation_prefix: "us_dw_settlement/"
    partition_strategy: "datetime"
    compression: "snappy"
  
  default_table_config:
    backup_strategy: "sequential"
    watermark_strategy: "automatic"
    validation:
      enable_data_quality_checks: true
      max_null_percentage: 3.0

# Settlement database tables
tables:
  settle_orders:
    cdc_strategy: "hybrid"
    cdc_timestamp_column: "created_at"
    cdc_id_column: "id"
    description: "Settlement orders with hybrid CDC (timestamp + ID)"
    processing:
      batch_size: 50000
    validation:
      enable_data_quality_checks: true
      max_null_percentage: 2.0

  # Add more settlement tables here as needed
  # settlement_claim_detail:
  #   cdc_strategy: "hybrid"
  #   cdc_timestamp_column: "updated_at"
  #   cdc_id_column: "id"
  #   description: "Settlement claim details"