# US Production Kuaisong Tracking Tables Pipeline (v1.2.0)
# High-frequency sync for tracking and order tables
# Sync frequency: Every 15 minutes (*/15 * * * *)

pipeline:
  name: "us_prod_kuaisong_tracking"
  description: "US Production Kuaisong tracking and order tables - 15 minute sync frequency"
  source: "US_PROD_RO_SSH"         # US Production (us-west-2) with SSH tunnel
  target: "redshift_default"       # QA Redshift cluster
  version: "1.2.0"                 # v1.2.0 CDC Intelligence Engine
  sync_frequency: "*/15 * * * *"    # Every 15 minutes
  
  processing:
    strategy: "sequential"         # Process tables one by one for stability
    batch_size: 25000             # Default batch size
    timeout_minutes: 15           # 15 minutes max per sync (larger batches need more time)
    max_parallel_tables: 1        # Sequential for controlled processing
    query_timeout_seconds: 90     # 90 seconds for larger batches
  
  s3:
    isolation_prefix: "us_prod_kuaisong/"
    partition_strategy: "datetime"
    compression: "snappy"
  
  # v1.2.0 CDC Intelligence settings
  cdc_settings:
    default_strategy: "timestamp_only"
    enable_watermark_validation: true
    enable_schema_validation: true
    fallback_to_legacy: true      # Maintain compatibility

# Table configurations for all kuaisong tracking tables
tables:
  # 1. Unified Tracking Info - ~500K records/day
  kuaisong.uni_tracking_info:
    cdc_strategy: "timestamp_only"
    cdc_timestamp_column: "update_time"    # UNIX timestamp
    timestamp_format: "unix"               # Specify UNIX timestamp format
    cdc_ordering: ["state", "update_time"] # Use composite index order
    additional_where: "state IS NOT NULL"  # Required for composite index usage
    
    description: "Unified tracking information with UNIX timestamp CDC + composite index optimization"
    target_name: "uni_tracking_info"       # Target table in Redshift
    
    processing:
      batch_size: 20000                    # Optimized batches for better performance
      enable_parallel_processing: false
      query_optimization: "use_index"      # Hint to use timestamp index
      
    validation:
      enable_data_quality_checks: true
      enable_schema_validation: true
      max_null_percentage: 5.0
      
    watermark_settings:
      enable_backup: true
      validation_mode: "strict"
      recovery_strategy: "automatic"
      
  # 2. Tracking Addon Spath - ~500K records/day  
  kuaisong.uni_tracking_addon_spath:
    cdc_strategy: "timestamp_only"
    cdc_timestamp_column: "create_at"      # DATETIME format
    timestamp_format: "datetime"           # Standard MySQL datetime
    
    description: "Tracking addon spath data with datetime CDC"
    target_name: "uni_tracking_addon_spath"
    
    processing:
      batch_size: 20000                    # Optimized batches for better performance
      enable_parallel_processing: false
      
    validation:
      enable_data_quality_checks: true
      enable_schema_validation: true
      max_null_percentage: 5.0
      
    watermark_settings:
      enable_backup: true
      validation_mode: "strict"
      recovery_strategy: "automatic"
      
  # 3. Tracking Spath - ~2M records/day (highest volume)
  kuaisong.uni_tracking_spath:
    cdc_strategy: "timestamp_only"
    cdc_timestamp_column: "pathTime"       # UNIX timestamp
    timestamp_format: "unix"               # Specify UNIX timestamp format
    
    description: "Tracking spath data - highest volume table"
    target_name: "uni_tracking_spath"
    
    processing:
      batch_size: 100000                    # Larger batches for highest volume table
      enable_parallel_processing: false
      query_timeout_seconds: 90            # Longer timeout for larger batches
      
    validation:
      enable_data_quality_checks: true
      enable_schema_validation: true
      max_null_percentage: 5.0
      
    watermark_settings:
      enable_backup: true
      validation_mode: "strict"
      recovery_strategy: "automatic"
      
    performance:
      memory_limit_mb: 6144               # 6GB for highest volume table (2M records/day)
      connection_timeout: 300
      query_timeout: 1800
      
  # 4. ECS Order Info - ~500K records/day
  kuaisong.ecs_order_info:
    cdc_strategy: "timestamp_only"
    cdc_timestamp_column: "add_time"       # UNIX timestamp
    timestamp_format: "unix"               # Specify UNIX timestamp format
    
    description: "ECS order information with UNIX timestamp CDC"
    target_name: "ecs_order_info"
    
    processing:
      batch_size: 20000                    # Optimized batches for better performance
      enable_parallel_processing: false
      
    validation:
      enable_data_quality_checks: true
      enable_schema_validation: true
      max_null_percentage: 5.0
      
    watermark_settings:
      enable_backup: true
      validation_mode: "strict"
      recovery_strategy: "automatic"
      
  # 5. Order Details - ~71M+ rows total, high incremental volume (HIGHEST PRIORITY)
  kuaisong.order_details:
    cdc_strategy: "id_only"                # No timestamp available - use ID-based incremental sync
    cdc_id_column: "id"                    # AUTO_INCREMENT=71714083 primary key
    
    description: "Order details - largest table requiring ID-based incremental sync"
    target_name: "order_details"
    
    processing:
      batch_size: 100000                   # Larger batches for high volume table
      enable_parallel_processing: false
      query_timeout_seconds: 180           # 3 minutes for larger batches
      
    validation:
      enable_data_quality_checks: true
      enable_schema_validation: true
      max_null_percentage: 10.0            # Higher tolerance for large transactional table
      
    watermark_settings:
      enable_backup: true
      validation_mode: "strict"
      recovery_strategy: "automatic"
      
    performance:
      memory_limit_mb: 8192                # 8GB for largest table
      connection_timeout: 300
      query_timeout: 3600                  # 1 hour max for very large incremental batches

    
  # 6. Uni Prealert Order - ~13.4M total, ID-based CDC
  kuaisong.uni_prealert_order:
    cdc_strategy: "id_only"
    cdc_id_column: "id"                    # AUTO_INCREMENT primary key
    
    description: "Prealert orders - high volume table with ID-based incremental sync"
    target_name: "uni_prealert_order"      # Target table in Redshift
    
    processing:
      batch_size: 50000                    # Larger batches for efficiency
      enable_parallel_processing: false
      
    validation:
      enable_schema_validation: true
      max_null_percentage: 15.0            # Allow nulls in optional fields
      
    watermark_settings:
      enable_backup: true
      validation_mode: "strict"
      recovery_strategy: "automatic"
      
    performance:
      memory_limit_mb: 4096                # 4GB for medium-large table

  # 7. Uni Sorting Parcels - ~139M+ total, high volume sorting operations
  kuaisong.uni_sorting_parcels:
    cdc_strategy: "id_only"
    cdc_id_column: "id"                    # AUTO_INCREMENT=139258973 primary key
    
    description: "Parcel sorting operations - high volume table with ID-based incremental sync (1 month initial load)"
    target_name: "uni_sorting_parcels"      # Target table in Redshift
    
    # Start from 1 month ago to avoid massive initial load
    start_from: "30 days ago"              # Only sync data from last 30 days
    initial_load_filter: "sort_time >= UNIX_TIMESTAMP(DATE_SUB(NOW(), INTERVAL 30 DAY))"
    
    processing:
      batch_size: 100000                    # Optimized for high volume sorting operations
      enable_parallel_processing: false
      query_timeout_seconds: 120           # 2 minutes for sorting data batches
      
    validation:
      enable_data_quality_checks: true
      enable_schema_validation: true
      max_null_percentage: 10.0            # Allow nulls in optional fields (dimensions, box_id)
      
    watermark_settings:
      enable_backup: true
      validation_mode: "strict"
      recovery_strategy: "automatic"
      
    performance:
      memory_limit_mb: 4096                # 4GB for high volume table
      connection_timeout: 300
      query_timeout: 1800                  # 30 minutes max

monitoring:
  enable_progress_tracking: true
  enable_performance_metrics: true
  alert_on_failures: true
